### ISSUE TITLE
Demo app does not request microphone access (in Chrome)

### ISSUE THREAD

**Issue by AndrewRayCode** [TwilioDevEd/client-quickstart-node#3]
When I try to make a call with the demo app (at a ngrok URL), it errors with this message:

> Twilio.Device Error: User denied access to microphone, or the web browser did not allow microphone access at this address.

However, microphone access is never requested in Chrome.

I have not yet configured the ngrok URL in the app settings and I'm not sure if that's causing the error. Either way, there may be a bug, either microphone access is never requested, or the error is incorrect when the ngrok URL is not configured in the app.

I have verified I do not have any ngrok related entries in Chrome's content management exceptions settings.

**Comment by dprothero** [comment]
As the OP discovered, this is due to Chrome requiring `https` for the microphone access. Using the `https` ngrok URL will solve the issue. Thanks to @AndrewRayCode for providing a PR to clarify this!
