### ISSUE TITLE
Publish twilio.js to NPM

### ISSUE THREAD

**Issue by AndrewRayCode** [TwilioDevEd/client-quickstart-node#5]
Not sure where to file this, but twilio.js should be in NPM. Fortunately in modern development we don't usually link to CDNs or include third party source code directly in our projects. That's why we use package managers like NPM.

**Comment by AndrewRayCode** [comment]
For now https://www.npmjs.com/package/twilio-client-mirror but still can't be loaded in node :(

**Comment by dprothero** [comment]
I will relay your request to the developers. I believe they are looking to address this.
