### ISSUE TITLE
Client Javascript SDK as a package

### ISSUE THREAD

**Issue by RUIFERNANDE5** [TwilioDevEd/client-quickstart-node#9]
Not really a issue with this repo itself, but I'm kinda in a hurry.
But I'd like to know why there isn't a npm / yarn package to [Twilio Client Javascript SDK 1.4](https://media.twiliocdn.com/sdk/js/client/v1.4/twilio.min.js).
I'm trying to use the voice service, following this repo as a tutorial, but implementing it in React Native.

Is this package for browser usage only? How could I have access to `Twilio.Client` on react-native? 

I already implemented a programmable-chat with success, using the provided packages `twilio-chat` and `twilio-common`.

Meanwhile, is there any way of importing a remote file or using a local javascript file (twilio.min.js) to a react-native app?

Thanks in advance.

**EDIT:**

Further research lead me to believe that this SDK only work for browsers since it has to deal with audio events, connection status etc. Correct me if I'm wrong. I'm now trying to implement [react-native-twilio-programmable-voice](https://github.com/hoxfon/react-native-twilio-programmable-voice) .

**Comment by piranna** [comment]
Are you trying to use Twilio SDK with ReactNative-web? I'm in the same thing currently, I hope we can get some response from Twilio itself...

**Comment by joliveros** [comment]
Hi @RUIFERNANDE5 , @piranna ,

If you are building a react-native app with webpack you can use the following loader to require the twilio client sdk https://www.npmjs.com/package/webpack-require-http
+1 to creating an npm module for https://media.twiliocdn.com/sdk/js/client/v1.4/twilio.min.js

**Comment by piranna** [comment]
> you can use the following loader to require the twilio client sdk https://www.npmjs.com/package/webpack-require-http

That's cool! :-D Although in that case I would include a bundled copy of the library... Or do a npm package and publish it, too :-) But this should be done by Twilio, not by a particular... That's not serious by their side...

**Comment by piranna** [comment]
By the way, the [non-minimified version of the library](https://media.twiliocdn.com/sdk/js/client/releases/1.4.24/twilio.js) seems that has been packaged by using browserify, so it should be easy to import...

**Comment by RUIFERNANDE5** [comment]
@piranna  @joliveros 
I'm actually trying to integrate it with react-native mobile ios/android. 
However I don't know how would this package work cuz of features like WebRTC that are intrinsic to browsers..

**Comment by joliveros** [comment]
@RUIFERNANDE5 ,
you could try patching the twilio.js file to use https://github.com/oney/react-native-webrtc
Besides that I'm not sure that we will support react-native specifically so this may be the only route.

**Comment by RUIFERNANDE5** [comment]
@joliveros What do you mean by patching?

**Comment by joliveros** [comment]
@RUIFERNANDE5, 
You could copy the twilio.js file locally and add these lines to the top of the file
```js
var WebRTC = require('react-native-webrtc');
var {
  RTCPeerConnection,
  RTCIceCandidate,
  RTCSessionDescription,
  RTCView,
  MediaStream,
  MediaStreamTrack,
  getUserMedia,
} = WebRTC;
```
which effectively provides the global WebRTC functions the script needs which are not available in react-native.

**Comment by piranna** [comment]
> You could copy the twilio.js file locally and add these lines to the top of the file

Nice trick! :-) So could this way support ReactNative both on Android, iOS and web/electron?

**Comment by piranna** [comment]
There's already a [react-native-twilio](https://www.npmjs.com/package/react-native-twilio) npm module, although it's one year old. There are some more recent forks, maybe it can be useful to your job and also we could contact to the original package maintainer to give us the module name to publish this more complete and recent one, how do you both see it?

**Comment by joliveros** [comment]
@piranna, 
That looks like a good start! Thanks for finding that. I have some experience with react-native. I will be happy to make a PR which updates the module. I may have something by Monday, unless you guys beat me to it. :smile:

**Comment by piranna** [comment]
> unless you guys beat me to it

I'll left you free the road :-) Good luck! :-D

The main problem that seems to be with `react-native-twilio` is that makes directly use of low level iOS libraries, and uses directly the REST API. I think the alternative proposed here of combining the oficial Twilio Javascript client with `react-native-webrtc` module would be a better and cleaner alternative.

**Comment by joliveros** [comment]
+1 to that. I'll give it a shot :smile:

**Comment by RUIFERNANDE5** [comment]
@joliveros @piranna currently trying, any idea how would I import the Twilio.Device? I tried `var Twilio = require('./twilio.js');` but got a empty object.

**Comment by piranna** [comment]
Maybe you would need to use de-browserify.

**Comment by RUIFERNANDE5** [comment]
I also needed to declare window.navigator.userAgent with a RN package

**Comment by RUIFERNANDE5** [comment]
@piranna I'll give it a shot, thanks for helping out guys!

**Comment by joliveros** [comment]
@RUIFERNANDE5 , @piranna ,

this seems to be a more up-to-date module: https://github.com/hoxfon/react-native-twilio-programmable-voice

**Comment by piranna** [comment]
> this seems to be a more up-to-date module: https://github.com/hoxfon/
react-native-twilio-programmable-voice

No ReactNative-web support :-(

**Comment by piranna** [comment]
@joliveros, have you got any progress? :-) If not, how do you suggest that I take a look at it?
